version: '2'
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    links:
      - phpfpm
    volumes:
      - ./html:/var/www/html/:ro
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 80:80
      - 443:443
  phpfpm:
    image: php:fpm
    container_name: phpfpm
    restart: always
    volumes:
      #- ./html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/php-fpm.conf:/usr/local/etc/php/php-fpm.conf
      - ./php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    volumes_from:
            - doc-symfony_app              
  doc-symfony_app:
    image: busybox
    container_name: lep-doc-symfony_app
    volumes:
            #- /var/www/html/var/cache
            #- /var/www/html/var/logs
            #- /var/www/html/var/sessions
       - ./html:/var/www/html
    command: /bin/sh -c "chown -R www-data:www-data /var/www/html"
