version: '2'
services:
  nginx:
    image: nginx
    container_name: lemp_nginx
    restart: always
    links:
      - phpfpm
    volumes:
      - ./html:/var/www/html/:ro
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 80:80
      - 443:443
  phpfpm:
    image: php:fpm
    container_name: lemp_phpfpm
    restart: always
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db
    links:
      - db
    environment:
      - DB_NAME=lemp_bdd
      - TABLE_PREFIX=lemp_
      - DB_HOST=lemp
      - DB_PASSWORD=password
  db:
    image: mariadb:latest
    container_name: lemp_mariadb
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
volumes:
  db-data:
    driver: local
