version: '2'
services:

  nginx:
      build: ./nginx/
      restart: always
      volumes:
        - ./app:/var/www/html/
        - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf
        - ./nginx/conf.d:/etc/nginx/conf.d
      ports:
        - 80
        - 443
